import {
  ActivityEntry,
  Asset,
  Expense,
  HomeDocument,
  Reminder,
  Room,
} from './models';

/* Seed data for the V1 mock backend.

   Product list generated with Gemini, then each item matched to its English
   Wikipedia article so the photo is a real shot of that product rather than
   generic stock. Images are hotlinked from Wikimedia (freely licensed); the
   asset card falls back to a category icon if one ever fails to load.

   Dates are generated relative to today so the seeded home always looks
   current — warranties expire soon, reminders fall due this week. */

function shift(days: number): string {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const SEED_ROOMS: Room[] = [
  {
    id: 'living-room',
    name: 'Living Room',
    image:
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    image:
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'bedroom-1',
    name: 'Bedroom 1',
    image:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'bedroom-2',
    name: 'Bedroom 2',
    image:
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'study',
    name: 'Study',
    image:
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'utility',
    name: 'Utility',
    image:
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?q=80&w=800&auto=format&fit=crop',
  },
];

export const SEED_ASSETS: Asset[] = [
  {
    id: 'a-sony-playstation-5',
    name: 'Sony PlayStation 5',
    brand: 'Sony',
    category: 'Electronics',
    roomId: 'living-room',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png/960px-Black_and_white_Playstation_5_base_edition_with_controller.png',
    purchaseDate: shift(-334),
    purchasePrice: 54990,
    warrantyExpiry: shift(30),
    serialNumber: 'PS5-88392019-IN',
    history: [],
  },
  {
    id: 'a-sony-bravia-55',
    name: 'Sony Bravia 55-inch 4K Smart TV',
    brand: 'Sony',
    category: 'Electronics',
    roomId: 'living-room',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/LG_smart_TV.jpg/960px-LG_smart_TV.jpg',
    purchaseDate: shift(-851),
    purchasePrice: 64990,
    warrantyExpiry: shift(-122),
    serialNumber: 'SNY-55X80J-40921',
    history: [],
  },
  {
    id: 'a-daikin-1-5',
    name: 'Daikin 1.5 Ton 5 Star Inverter AC',
    brand: 'Daikin',
    category: 'Climate',
    roomId: 'living-room',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/MITSUBISHI_ELECTRIC_WINDOW_TYPE_AIR_CONDITIONER_OUTDOOR_UNIT.jpg/960px-MITSUBISHI_ELECTRIC_WINDOW_TYPE_AIR_CONDITIONER_OUTDOOR_UNIT.jpg',
    purchaseDate: shift(-547),
    purchasePrice: 45500,
    warrantyExpiry: shift(-182),
    serialNumber: 'DKN-AC15T-77210',
    history: [
      {
        id: 'h-a-daikin-1-5-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-246),
        cost: 1800,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-wooden-3-seater',
    name: 'Wooden 3-Seater Fabric Sofa',
    brand: 'Urban Ladder',
    category: 'Furniture',
    roomId: 'living-room',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Slaapbank2.JPG/960px-Slaapbank2.JPG',
    purchaseDate: shift(-1094),
    purchasePrice: 28500,
    history: [],
  },
  {
    id: 'a-luminous-zelio-1100',
    name: 'Luminous Zelio 1100 Sine Wave Inverter',
    brand: 'Luminous',
    category: 'Appliances',
    roomId: 'living-room',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/An_Inverter.jpg/960px-An_Inverter.jpg',
    purchaseDate: shift(-426),
    purchasePrice: 18500,
    warrantyExpiry: shift(8),
    serialNumber: 'LUM-ZEL1100-9921',
    history: [
      {
        id: 'h-a-luminous-zelio-1100-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-192),
        cost: 2170,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-lg-260l-3',
    name: 'LG 260L 3 Star Frost Free Double Door Refrigerator',
    brand: 'LG',
    category: 'Kitchen',
    roomId: 'kitchen',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Open_refrigerator_with_food_at_night.jpg/960px-Open_refrigerator_with_food_at_night.jpg',
    purchaseDate: shift(-608),
    purchasePrice: 26990,
    warrantyExpiry: shift(-243),
    serialNumber: 'LG-RF260L-00492',
    history: [
      {
        id: 'h-a-lg-260l-3-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-274),
        cost: 2540,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-kent-grand-plus',
    name: 'Kent Grand Plus RO Water Purifier',
    brand: 'Kent',
    category: 'Kitchen',
    roomId: 'kitchen',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Clickon_Water_Dispenser.jpg/960px-Clickon_Water_Dispenser.jpg',
    purchaseDate: shift(-334),
    purchasePrice: 16500,
    warrantyExpiry: shift(30),
    serialNumber: 'KNT-RO-883921',
    history: [],
  },
  {
    id: 'a-ifb-23l-convection',
    name: 'IFB 23L Convection Microwave Oven',
    brand: 'IFB',
    category: 'Kitchen',
    roomId: 'kitchen',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Panasonic_NN-SD69LS_20220410.jpg/960px-Panasonic_NN-SD69LS_20220410.jpg',
    purchaseDate: shift(-243),
    purchasePrice: 11800,
    warrantyExpiry: shift(19),
    serialNumber: 'IFB-MW23C-11029',
    history: [],
  },
  {
    id: 'a-prestige-iris-750w',
    name: 'Prestige Iris 750W Mixer Grinder',
    brand: 'Prestige',
    category: 'Kitchen',
    roomId: 'kitchen',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Food_Processor_2.jpg/960px-Food_Processor_2.jpg',
    purchaseDate: shift(-456),
    purchasePrice: 3299,
    warrantyExpiry: shift(26),
    serialNumber: 'PRST-MG750-3021',
    history: [
      {
        id: 'h-a-prestige-iris-750w-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-205),
        cost: 2910,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-pigeon-3-burner',
    name: 'Pigeon 3 Burner Glass Top Gas Stove',
    brand: 'Pigeon',
    category: 'Kitchen',
    roomId: 'kitchen',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/9/99/Gas_stove.jpg',
    purchaseDate: shift(-1277),
    purchasePrice: 2800,
    warrantyExpiry: shift(-912),
    serialNumber: 'PGN-GS3B-7741',
    history: [
      {
        id: 'h-a-pigeon-3-burner-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-575),
        cost: 3280,
        provider: 'UrbanCare Services',
      },
      {
        id: 'h-a-pigeon-3-burner-1',
        kind: 'repair',
        title: 'Part replacement',
        date: shift(-1021),
        cost: 4440,
        provider: 'Pigeon Authorised',
      },
    ],
  },
  {
    id: 'a-samsung-galaxy-s23',
    name: 'Samsung Galaxy S23 5G',
    brand: 'Samsung',
    category: 'Electronics',
    roomId: 'bedroom-1',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Galaxy_S23.png/960px-Galaxy_S23.png',
    purchaseDate: shift(-182),
    purchasePrice: 74999,
    warrantyExpiry: shift(182),
    serialNumber: 'R58M302910X',
    history: [],
  },
  {
    id: 'a-voltas-1-2',
    name: 'Voltas 1.2 Ton Split AC',
    brand: 'Voltas',
    category: 'Climate',
    roomId: 'bedroom-1',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/MITSUBISHI_ELECTRIC_WINDOW_TYPE_AIR_CONDITIONER_OUTDOOR_UNIT.jpg/960px-MITSUBISHI_ELECTRIC_WINDOW_TYPE_AIR_CONDITIONER_OUTDOOR_UNIT.jpg',
    purchaseDate: shift(-486),
    purchasePrice: 32000,
    warrantyExpiry: shift(-122),
    serialNumber: 'VLT-12SAC-55109',
    history: [
      {
        id: 'h-a-voltas-1-2-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-219),
        cost: 2050,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-orient-electric-stand',
    name: 'Orient Electric Stand Fan',
    brand: 'Orient',
    category: 'Climate',
    roomId: 'bedroom-1',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Hatari_18_inch_fan.jpg/960px-Hatari_18_inch_fan.jpg',
    purchaseDate: shift(-152),
    purchasePrice: 2400,
    warrantyExpiry: shift(578),
    serialNumber: 'ORT-SF-90123',
    history: [],
  },
  {
    id: 'a-king-size-teak',
    name: 'King Size Teak Wood Bed Frame',
    brand: 'Wakefit',
    category: 'Furniture',
    roomId: 'bedroom-1',
    image:
      'https://upload.wikimedia.org/wikipedia/en/3/3a/Four_Poster_Bed_350b.jpg',
    purchaseDate: shift(-912),
    purchasePrice: 34999,
    history: [],
  },
  {
    id: 'a-mi-air-purifier',
    name: 'Mi Air Purifier 4',
    brand: 'Xiaomi',
    category: 'Climate',
    roomId: 'bedroom-1',
    purchaseDate: shift(-699),
    purchasePrice: 14999,
    warrantyExpiry: shift(30),
    serialNumber: 'MI-AP4-883019',
    history: [
      {
        id: 'h-a-mi-air-purifier-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-315),
        cost: 2420,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-hp-pavilion-15',
    name: 'HP Pavilion 15 Laptop',
    brand: 'HP',
    category: 'Electronics',
    roomId: 'bedroom-2',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Laptop_collage.jpg/960px-Laptop_collage.jpg',
    purchaseDate: shift(-578),
    purchasePrice: 62500,
    warrantyExpiry: shift(-213),
    serialNumber: '5CD12039K2',
    history: [],
  },
  {
    id: 'a-crompton-silentpro-ceiling',
    name: 'Crompton SilentPro Ceiling Fan',
    brand: 'Crompton',
    category: 'Climate',
    roomId: 'bedroom-2',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Ventilatore_a_soffitto_%283%29.png/960px-Ventilatore_a_soffitto_%283%29.png',
    purchaseDate: shift(-304),
    purchasePrice: 5200,
    warrantyExpiry: shift(426),
    serialNumber: 'CRM-CF-11928',
    history: [],
  },
  {
    id: 'a-oneplus-pad-tablet',
    name: 'OnePlus Pad Tablet',
    brand: 'OnePlus',
    category: 'Electronics',
    roomId: 'bedroom-2',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/12.9_iPad_Pro_1st_Gen_And_Galaxy_Tab_S8_Ultra_Size_Comparison.jpg/960px-12.9_iPad_Pro_1st_Gen_And_Galaxy_Tab_S8_Ultra_Size_Comparison.jpg',
    purchaseDate: shift(-91),
    purchasePrice: 37999,
    warrantyExpiry: shift(274),
    serialNumber: '1P-PAD-99210',
    history: [],
  },
  {
    id: 'a-wooden-study-desk',
    name: 'Wooden Study Desk with Shelf',
    brand: 'Pepperfry',
    category: 'Furniture',
    roomId: 'bedroom-2',
    purchaseDate: shift(-730),
    purchasePrice: 8500,
    history: [],
  },
  {
    id: 'a-havells-solero-15l',
    name: 'Havells Solero 15L Storage Water Heater',
    brand: 'Havells',
    category: 'Appliances',
    roomId: 'bedroom-2',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Water_heater_bathroom.JPG/960px-Water_heater_bathroom.JPG',
    purchaseDate: shift(-365),
    purchasePrice: 8900,
    warrantyExpiry: shift(365),
    serialNumber: 'HVL-WH15L-33019',
    history: [],
  },
  {
    id: 'a-bosch-7kg-fully',
    name: 'Bosch 7kg Fully Automatic Front Load Washing Machine',
    brand: 'Bosch',
    category: 'Appliances',
    roomId: 'utility',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/e/ec/LG_%EB%93%9C%EB%9F%BC%EC%84%B8%ED%83%81%EA%B8%B0%EC%99%80_%EC%8B%9D%EA%B8%B0%EC%84%B8%EC%B2%99%EA%B8%B0%2C_%EC%98%81%EA%B5%AD%EC%84%9C_%EB%AC%BC%EC%82%AC%EC%9A%A9_%ED%9A%A8%EC%9C%A8_%EC%B5%9C%EC%9A%B0%EC%88%98_%EC%A0%9C%ED%92%88_%EC%88%98%EC%83%81.jpg',
    purchaseDate: shift(-456),
    purchasePrice: 34500,
    warrantyExpiry: shift(274),
    serialNumber: 'BSH-WM7K-90211',
    history: [
      {
        id: 'h-a-bosch-7kg-fully-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-205),
        cost: 2790,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-ao-smith-25l',
    name: 'AO Smith 25L Vertical Water Heater Geyser',
    brand: 'AO Smith',
    category: 'Appliances',
    roomId: 'utility',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Chauffe-eau_%C3%A9lectrique_50L_mural_vertical.jpg/960px-Chauffe-eau_%C3%A9lectrique_50L_mural_vertical.jpg',
    purchaseDate: shift(-1064),
    purchasePrice: 12800,
    warrantyExpiry: shift(30),
    serialNumber: 'AOS-GEY25-77102',
    history: [
      {
        id: 'h-a-ao-smith-25l-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-479),
        cost: 3160,
        provider: 'UrbanCare Services',
      },
      {
        id: 'h-a-ao-smith-25l-1',
        kind: 'repair',
        title: 'Part replacement',
        date: shift(-851),
        cost: 3880,
        provider: 'AO Smith Authorised',
      },
    ],
  },
  {
    id: 'a-karcher-k2-high',
    name: 'Karcher K2 High Pressure Washer',
    brand: 'Karcher',
    category: 'Other',
    roomId: 'utility',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/H%C3%B6gtryckstv%C3%A4tt_-_Pressure_washer_-_Ystad-2011.jpg/960px-H%C3%B6gtryckstv%C3%A4tt_-_Pressure_washer_-_Ystad-2011.jpg',
    purchaseDate: shift(-243),
    purchasePrice: 8200,
    warrantyExpiry: shift(122),
    serialNumber: 'KRC-K2PW-09218',
    history: [],
  },
  {
    id: 'a-heavy-duty-metal',
    name: 'Heavy Duty Metal Utility Storage Rack',
    brand: 'Amazon Basics',
    category: 'Furniture',
    roomId: 'utility',
    purchaseDate: shift(-426),
    purchasePrice: 3200,
    history: [],
  },
  {
    id: 'a-eureka-forbes-vac',
    name: 'Eureka Forbes Vac Easy Vacuum Cleaner',
    brand: 'Eureka Forbes',
    category: 'Appliances',
    roomId: 'utility',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg/960px-Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg',
    purchaseDate: shift(-486),
    purchasePrice: 6500,
    warrantyExpiry: shift(-122),
    serialNumber: 'EF-VC-66201',
    history: [
      {
        id: 'h-a-eureka-forbes-vac-0',
        kind: 'service',
        title: 'Annual service',
        date: shift(-219),
        cost: 1930,
        provider: 'UrbanCare Services',
      },
    ],
  },
  {
    id: 'a-apple-macbook-air',
    name: 'Apple MacBook Air M2',
    brand: 'Apple',
    category: 'Electronics',
    roomId: 'study',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Macbook_Air_15_inch_-_2_%28blurred%29.jpg/960px-Macbook_Air_15_inch_-_2_%28blurred%29.jpg',
    purchaseDate: shift(-243),
    purchasePrice: 105000,
    warrantyExpiry: shift(122),
    serialNumber: 'C02G9012MD6M',
    history: [],
  },
  {
    id: 'a-dell-27-inch',
    name: 'Dell 27-inch 4K Monitor',
    brand: 'Dell',
    category: 'Electronics',
    roomId: 'study',
    purchaseDate: shift(-1064),
    purchasePrice: 28500,
    warrantyExpiry: shift(30),
    serialNumber: 'CN-09M321-72801',
    history: [],
  },
  {
    id: 'a-green-soul-ergonomic',
    name: 'Green Soul Ergonomic Office Chair',
    brand: 'Green Soul',
    category: 'Furniture',
    roomId: 'study',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/4/4b/Desk_chair.jpg',
    purchaseDate: shift(-182),
    purchasePrice: 12500,
    warrantyExpiry: shift(182),
    serialNumber: 'GS-EC-33921',
    history: [],
  },
  {
    id: 'a-canon-imageclass-laser',
    name: 'Canon ImageCLASS Laser Printer',
    brand: 'Canon',
    category: 'Electronics',
    roomId: 'study',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/b/b8/Hp_laserjet_4200dtns.jpg',
    purchaseDate: shift(-669),
    purchasePrice: 16200,
    warrantyExpiry: shift(-304),
    serialNumber: 'CNN-LBP6030-9912',
    history: [],
  },
  {
    id: 'a-syska-smart-led',
    name: 'Syska Smart LED Desk Lamp',
    brand: 'Syska',
    category: 'Electronics',
    roomId: 'study',
    image:
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Anglepoise_1227.jpg/960px-Anglepoise_1227.jpg',
    purchaseDate: shift(-122),
    purchasePrice: 1499,
    warrantyExpiry: shift(243),
    serialNumber: 'SYS-DL-10928',
    history: [],
  },
];

export const SEED_REMINDERS: Reminder[] = [
  {
    id: 'r-1',
    title: 'Water purifier filter change',
    assetId: 'a-kent-grand-plus',
    dueDate: shift(-4),
    repeat: 'quarterly',
    completed: false,
    notes: 'Sediment and carbon filter both due.',
  },
  {
    id: 'r-2',
    title: 'Electricity bill',
    dueDate: shift(1),
    repeat: 'monthly',
    completed: false,
  },
  {
    id: 'r-3',
    title: 'AC deep clean before summer',
    assetId: 'a-daikin-1-5',
    dueDate: shift(3),
    repeat: 'yearly',
    completed: false,
  },
  {
    id: 'r-4',
    title: 'Washing machine drum clean',
    assetId: 'a-bosch-7kg-fully',
    dueDate: shift(6),
    repeat: 'quarterly',
    completed: false,
  },
  {
    id: 'r-5',
    title: 'Internet bill',
    dueDate: shift(9),
    repeat: 'monthly',
    completed: false,
  },
  {
    id: 'r-6',
    title: 'Geyser servicing',
    assetId: 'a-havells-solero-15l',
    dueDate: shift(14),
    repeat: 'yearly',
    completed: false,
  },
  {
    id: 'r-7',
    title: 'Chimney & stove deep clean',
    assetId: 'a-pigeon-3-burner',
    dueDate: shift(21),
    repeat: 'quarterly',
    completed: false,
  },
  {
    id: 'r-8',
    title: 'Inverter battery water top-up',
    assetId: 'a-luminous-zelio-1100',
    dueDate: shift(27),
    repeat: 'quarterly',
    completed: false,
  },
  {
    id: 'r-9',
    title: 'Ceiling fan dusting',
    assetId: 'a-crompton-silentpro-ceiling',
    dueDate: shift(34),
    repeat: 'quarterly',
    completed: false,
  },
  {
    id: 'r-10',
    title: 'Laptop warranty review',
    assetId: 'a-hp-pavilion-15',
    dueDate: shift(41),
    repeat: 'none',
    completed: false,
  },
  {
    id: 'r-11',
    title: 'Vacuum filter wash',
    assetId: 'a-eureka-forbes-vac',
    dueDate: shift(-22),
    repeat: 'monthly',
    completed: true,
  },
  {
    id: 'r-12',
    title: 'Fridge coil cleaning',
    assetId: 'a-lg-260l-3',
    dueDate: shift(-35),
    repeat: 'yearly',
    completed: true,
  },
];

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'e-1',
    title: 'Electricity',
    amount: 5240,
    date: shift(-3),
    category: 'Utilities',
  },
  {
    id: 'e-2',
    title: 'Water',
    amount: 680,
    date: shift(-5),
    category: 'Utilities',
  },
  {
    id: 'e-3',
    title: 'Internet',
    amount: 1199,
    date: shift(-8),
    category: 'Utilities',
  },
  {
    id: 'e-4',
    title: 'Cooking gas cylinder',
    amount: 910,
    date: shift(-11),
    category: 'Utilities',
  },
  {
    id: 'e-5',
    title: 'Society maintenance',
    amount: 3500,
    date: shift(-12),
    category: 'Services',
  },
  {
    id: 'e-6',
    title: 'Deep cleaning service',
    amount: 2800,
    date: shift(-16),
    category: 'Services',
  },
  {
    id: 'e-7',
    title: 'AC gas top-up',
    amount: 2400,
    date: shift(-19),
    category: 'Maintenance',
    assetId: 'a-daikin-1-5',
  },
  {
    id: 'e-8',
    title: 'Plumbing fix',
    amount: 1450,
    date: shift(-23),
    category: 'Repairs',
  },
  {
    id: 'e-9',
    title: 'Electricity',
    amount: 5980,
    date: shift(-34),
    category: 'Utilities',
  },
  {
    id: 'e-10',
    title: 'Water',
    amount: 640,
    date: shift(-36),
    category: 'Utilities',
  },
  {
    id: 'e-11',
    title: 'Internet',
    amount: 1199,
    date: shift(-38),
    category: 'Utilities',
  },
  {
    id: 'e-12',
    title: 'Society maintenance',
    amount: 3500,
    date: shift(-42),
    category: 'Services',
  },
  {
    id: 'e-13',
    title: 'Washing machine repair',
    amount: 3100,
    date: shift(-47),
    category: 'Repairs',
    assetId: 'a-bosch-7kg-fully',
  },
  {
    id: 'e-14',
    title: 'Pest control',
    amount: 1800,
    date: shift(-52),
    category: 'Services',
  },
];

export const SEED_DOCUMENTS: HomeDocument[] = [
  {
    id: 'd-1',
    title: 'Apple MacBook Air M2 — Invoice',
    kind: 'Invoice',
    assetId: 'a-apple-macbook-air',
    addedDate: shift(-243),
    fileName: 'apple-macbook-air-invoice.pdf',
    sizeLabel: '180 KB',
  },
  {
    id: 'd-2',
    title: 'Apple MacBook Air M2 — Warranty',
    kind: 'Warranty',
    assetId: 'a-apple-macbook-air',
    addedDate: shift(-242),
    fileName: 'apple-macbook-air-warranty.pdf',
    sizeLabel: '120 KB',
  },
  {
    id: 'd-3',
    title: 'Samsung Galaxy S23 5G — Invoice',
    kind: 'Invoice',
    assetId: 'a-samsung-galaxy-s23',
    addedDate: shift(-182),
    fileName: 'samsung-galaxy-s23-invoice.pdf',
    sizeLabel: '220 KB',
  },
  {
    id: 'd-4',
    title: 'Samsung Galaxy S23 5G — Warranty',
    kind: 'Warranty',
    assetId: 'a-samsung-galaxy-s23',
    addedDate: shift(-181),
    fileName: 'samsung-galaxy-s23-warranty.pdf',
    sizeLabel: '145 KB',
  },
  {
    id: 'd-5',
    title: 'Sony Bravia 55-inch 4K Smart TV — Invoice',
    kind: 'Invoice',
    assetId: 'a-sony-bravia-55',
    addedDate: shift(-851),
    fileName: 'sony-bravia-55-invoice.pdf',
    sizeLabel: '260 KB',
  },
  {
    id: 'd-6',
    title: 'Sony Bravia 55-inch 4K Smart TV — Warranty',
    kind: 'Warranty',
    assetId: 'a-sony-bravia-55',
    addedDate: shift(-850),
    fileName: 'sony-bravia-55-warranty.pdf',
    sizeLabel: '170 KB',
  },
  {
    id: 'd-7',
    title: 'HP Pavilion 15 Laptop — Invoice',
    kind: 'Invoice',
    assetId: 'a-hp-pavilion-15',
    addedDate: shift(-578),
    fileName: 'hp-pavilion-15-invoice.pdf',
    sizeLabel: '300 KB',
  },
  {
    id: 'd-8',
    title: 'HP Pavilion 15 Laptop — Warranty',
    kind: 'Warranty',
    assetId: 'a-hp-pavilion-15',
    addedDate: shift(-577),
    fileName: 'hp-pavilion-15-warranty.pdf',
    sizeLabel: '195 KB',
  },
  {
    id: 'd-9',
    title: 'Sony PlayStation 5 — Invoice',
    kind: 'Invoice',
    assetId: 'a-sony-playstation-5',
    addedDate: shift(-334),
    fileName: 'sony-playstation-5-invoice.pdf',
    sizeLabel: '340 KB',
  },
  {
    id: 'd-10',
    title: 'Sony PlayStation 5 — Warranty',
    kind: 'Warranty',
    assetId: 'a-sony-playstation-5',
    addedDate: shift(-333),
    fileName: 'sony-playstation-5-warranty.pdf',
    sizeLabel: '220 KB',
  },
  {
    id: 'd-11',
    title: 'Daikin 1.5 Ton 5 Star Inverter AC — Invoice',
    kind: 'Invoice',
    assetId: 'a-daikin-1-5',
    addedDate: shift(-547),
    fileName: 'daikin-1-5-invoice.pdf',
    sizeLabel: '380 KB',
  },
  {
    id: 'd-12',
    title: 'Daikin 1.5 Ton 5 Star Inverter AC — Warranty',
    kind: 'Warranty',
    assetId: 'a-daikin-1-5',
    addedDate: shift(-546),
    fileName: 'daikin-1-5-warranty.pdf',
    sizeLabel: '245 KB',
  },
  {
    id: 'd-13',
    title: 'OnePlus Pad Tablet — Invoice',
    kind: 'Invoice',
    assetId: 'a-oneplus-pad-tablet',
    addedDate: shift(-91),
    fileName: 'oneplus-pad-tablet-invoice.pdf',
    sizeLabel: '420 KB',
  },
  {
    id: 'd-14',
    title: 'OnePlus Pad Tablet — Warranty',
    kind: 'Warranty',
    assetId: 'a-oneplus-pad-tablet',
    addedDate: shift(-90),
    fileName: 'oneplus-pad-tablet-warranty.pdf',
    sizeLabel: '270 KB',
  },
  {
    id: 'd-15',
    title: 'Home Insurance Policy 2026',
    kind: 'Insurance',
    addedDate: shift(-210),
    fileName: 'home-insurance-2026.pdf',
    sizeLabel: '840 KB',
  },
  {
    id: 'd-16',
    title: 'Flat Rental Agreement',
    kind: 'Other',
    addedDate: shift(-400),
    fileName: 'rental-agreement.pdf',
    sizeLabel: '1.2 MB',
  },
  {
    id: 'd-17',
    title: 'Apple MacBook Air M2 — User Manual',
    kind: 'Manual',
    assetId: 'a-apple-macbook-air',
    addedDate: shift(-241),
    fileName: 'user-manual.pdf',
    sizeLabel: '3.4 MB',
  },
];

export const SEED_ACTIVITY: ActivityEntry[] = [
  {
    id: 'ac-1',
    icon: 'box',
    title: 'Added OnePlus Pad Tablet',
    context: 'Bedroom 2',
    at: shift(-91),
  },
  {
    id: 'ac-2',
    icon: 'check-circle',
    title: 'Completed Vacuum filter wash',
    context: 'Reminders',
    at: shift(-22),
  },
  {
    id: 'ac-3',
    icon: 'receipt',
    title: 'Logged AC gas top-up',
    context: 'Maintenance · ₹2,400',
    at: shift(-19),
  },
  {
    id: 'ac-4',
    icon: 'box',
    title: 'Added Syska Smart LED Desk Lamp',
    context: 'Study',
    at: shift(-122),
  },
  {
    id: 'ac-5',
    icon: 'file-plus',
    title: 'Added a new document',
    context: 'Invoice · Home Insurance',
    at: shift(-30),
  },
  {
    id: 'ac-6',
    icon: 'wrench',
    title: 'Washing machine repair logged',
    context: 'Utility',
    at: shift(-47),
  },
];
